# Simple workflow for deploying static content to GitHub Pages
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!

  # End additional job steps!!
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add steps here!!
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: ./
        continue-on-error: true
      - name: stylelint
        uses: actions-hub/stylelint@master
        continue-on-error: true
      # End additional steps!!
